version: '2'
services:
  db:
    image: postgres:13
    # postgres_version: 13
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always             # run as a service
    volumes:
        - ./pgdata:/var/lib/postgresql/data/pgdata

  web:
    image: odoo:14
    # odoo_version: 14
    depends_on:
      - db
    expose:
      - "8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    
